### ISSUE TITLE
assert in line drawer.py

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/Ognon#18]
```
Traceback (most recent call last):
  File "/home/leon/proj/Ognon/ognon/server.py", line 58, in call_function
    return f(*args, **kwargs)
  File "/home/leon/proj/Ognon/ognon/control/__init__.py", line 23, in wrapped
    return fun(cursor, *args, **kwargs)
  File "/home/leon/proj/Ognon/ognon/control/drawer.py", line 18, in draw
    assert e.lines[-1].coords[-2:] == coords[:2]
AttributeError: 'AnimRef' object has no attribute 'lines'
```

??

**Comment by LeonLenclos** [comment]
bad practice ?
